version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vinu@7852495
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql_service
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Vinu@7852495
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
